<?xml version="1.0"?>
<!-- conveyor on top of car -->
<robot name="bixi" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="M_PI" value="3.1415926535897931"/>

    <!-- Base Size -->
    <property name="conv_mass" value="1" />
    <property name="conv_x_size" value="0.7" />
    <property name="conv_y_size" value="0.22" />
    <property name="conv_z_size" value="0.02" />
    <property name="base_z_size" value="0.1" />
    <link name="conveyor_link">
        <visual>
            <origin xyz="-${conv_x_size/2} 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://bixi_description/meshes/conveyor.dae" scale="1.64 3.28 3.28" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="-${conv_x_size/2} 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${conv_x_size} ${conv_y_size} ${conv_z_size}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${conv_mass}" />
            <origin xyz="0 0 0" />
            <inertia ixx="${1/12*conv_mass*(conv_x_size*conv_x_size + conv_z_size*conv_z_size)}"
                iyy="${1/12*conv_mass*(conv_y_size*conv_y_size + conv_z_size*conv_z_size)}"
                izz="${1/12*conv_mass*(conv_y_size*conv_y_size + conv_x_size*conv_x_size)}"
                ixy="0" ixz="0" iyz="0" />
        </inertial>
    </link>
    <link name="conveyor_extend_link">
        <visual>
            <origin xyz="-${conv_x_size/2} 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://bixi_description/meshes/conveyor_extend.dae" scale="1.64 3.28 3.28" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="-${conv_x_size/2} 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${conv_x_size} ${conv_y_size} ${conv_z_size}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${conv_mass}" />
            <origin xyz="0 0 0" />
            <inertia ixx="${1/12*conv_mass*(conv_x_size*conv_x_size + conv_z_size*conv_z_size)}"
                iyy="${1/12*conv_mass*(conv_y_size*conv_y_size + conv_z_size*conv_z_size)}"
                izz="${1/12*conv_mass*(conv_y_size*conv_y_size + conv_x_size*conv_x_size)}"
                ixy="0" ixz="0" iyz="0" />
        </inertial>
    </link>

    <joint name="conveyor_joint" type="revolute">
        <origin xyz="0.4 0 ${base_z_size+conv_z_size}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="conveyor_link" />
        <axis xyz="0 1 0" />
        <limit lower="-0.15" upper="${M_PI/2}" effort="10" velocity="0.1" />
    </joint>
    <joint name="conveyor_extend_joint" type="prismatic">
        <origin xyz="-${conv_x_size/2} 0 0" rpy="0 0 0" />
        <parent link="conveyor_link" />
        <child link="conveyor_extend_link" />
        <axis xyz="-1 0 0" />
        <limit lower="-0.35" upper="0.35" effort="10" velocity="0.1" />
    </joint>

</robot>
